=== yuxiaoli/rsshub-monitor/data/servers.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string",
        "format": "uri"
      },
      "location": {
        "type": "string"
      },
      "maintainer": {
        "type": "string"
      },
      "maintainerUrl": {
        "type": "string",
        "format": "uri"
      },
      "online": {
        "type": "boolean"
      },
      "lastChecked": {
        "type": "string",
        "format": "date-time"
      }
    },
    "required": ["url", "location", "maintainer", "maintainerUrl", "online", "lastChecked"]
  }
}

=== yuxiaoli/rsshub-monitor/data/servers.json
[
  {
    "url": "https://rsshub.rssforever.com",
    "location": "ğŸ‡¦ğŸ‡ª",
    "maintainer": "Stille",
    "maintainerUrl": "https://www.ioiox.com",
    "online": true,
    "lastChecked": "2025-03-18T23:55:06.490410Z"
  },
  {
    "url": "https://hub.slarker.me",
    "location": "ğŸ‡ºğŸ‡¸",
    "maintainer": "Slarker",
    "maintainerUrl": "https://slarker.me",
    "online": true,
    "lastChecked": "2025-03-18T23:55:07.124530Z"
  },
  {
    "url": "https://rsshub.pseudoyu.com",
    "location": "ğŸ‡©ğŸ‡ª",
    "maintainer": "pseudoyu",
    "maintainerUrl": "https://github.com/pseudoyu",
    "online": true,
    "lastChecked": "2025-03-18T23:55:16.621269Z"
  },
  {
    "url": "https://rsshub.rss.tips",
    "location": "ğŸ‡ºğŸ‡¸",
    "maintainer": "AboutRSS",
    "maintainerUrl": "https://github.com/AboutRSS/ALL-about-RSS",
    "online": true,
    "lastChecked": "2025-03-18T23:55:17.084547Z"
  },
  {
    "url": "https://rsshub.ktachibana.party",
    "location": "ğŸ‡ºğŸ‡¸",
    "maintainer": "KTachibanaM",
    "maintainerUrl": "https://github.com/KTachibanaM",
    "online": false,
    "lastChecked": "2025-03-18T23:55:21.295709Z"
  },
  {
    "url": "https://rsshub.woodland.cafe",
    "location": "ğŸ‡©ğŸ‡ª",
    "maintainer": "untitaker",
    "maintainerUrl": "https://github.com/untitaker",
    "online": false,
    "lastChecked": "2025-03-18T23:55:22.306018Z"
  },
  {
    "url": "https://rss.owo.nz",
    "location": "ğŸ‡©ğŸ‡ª",
    "maintainer": "Vincent Yang",
    "maintainerUrl": "https://missuo.me",
    "online": true,
    "lastChecked": "2025-03-18T23:55:22.751412Z"
  },
  {
    "url": "https://rss.wudifeixue.com",
    "location": "ğŸ‡¨ğŸ‡¦",
    "maintainer": "wudifeixue",
    "maintainerUrl": "https://github.com/wudifeixue",
    "online": true,
    "lastChecked": "2025-03-18T23:55:23.595475Z"
  },
  {
    "url": "https://yangzhi.app",
    "location": "ğŸ‡¯ğŸ‡µ",
    "maintainer": "ä»°æ­¢",
    "maintainerUrl": "https://yangzhi.org",
    "online": true,
    "lastChecked": "2025-03-18T23:55:24.239591Z"
  },
  {
    "url": "https://rss.littlebaby.life/rsshub",
    "location": "ğŸ‡ºğŸ‡¸",
    "maintainer": "yuanhong",
    "maintainerUrl": "https://github.com/yuanhong078",
    "online": true,
    "lastChecked": "2025-03-18T23:55:25.241626Z"
  },
  {
    "url": "https://rsshub.henry.wang",
    "location": "ğŸ‡¬ğŸ‡§",
    "maintainer": "HenryQW",
    "maintainerUrl": "https://github.com/HenryQW",
    "online": true,
    "lastChecked": "2025-03-18T23:55:26.171702Z"
  },
  {
    "url": "https://rsshub.speednet.icu",
    "location": "ğŸ‡­ğŸ‡°",
    "maintainer": "freeintweb",
    "maintainerUrl": "https://github.com/freeintweb",
    "online": true,
    "lastChecked": "2025-03-18T23:55:27.139526Z"
  },
  {
    "url": "https://holoxx.f5.si/",
    "location": "ğŸ‡¯ğŸ‡µ",
    "maintainer": "Vania",
    "maintainerUrl": "https://note.com/vania",
    "online": true,
    "lastChecked": "2025-03-18T23:55:29.168368Z"
  },
  {
    "url": "https://hub.rss.direct",
    "location": "ğŸ‡¸ğŸ‡¬",
    "maintainer": "Eric Zhu",
    "maintainerUrl": "https://github.com/ericyzhu",
    "online": false,
    "lastChecked": "2025-03-18T23:55:29.525994Z"
  },
  {
    "url": "https://rsshub.umzzz.com",
    "location": "ğŸ‡­ğŸ‡°",
    "maintainer": "nesay",
    "maintainerUrl": "https://umzzz.com",
    "online": false,
    "lastChecked": "2025-03-18T23:55:34.200163Z"
  },
  {
    "url": "https://rsshub.isrss.com",
    "location": "ğŸ‡°ğŸ‡·",
    "maintainer": "isRSS",
    "maintainerUrl": "https://isrss.com",
    "online": true,
    "lastChecked": "2025-03-18T23:55:35.128538Z"
  },
  {
    "url": "https://rsshub.thzu.xyz",
    "location": "ğŸ‡­ğŸ‡°",
    "maintainer": "thzu",
    "maintainerUrl": "https://thzu.xyz",
    "online": true,
    "lastChecked": "2025-03-18T23:55:36.278231Z"
  },
  {
    "url": "https://rsshub.email-once.com",
    "location": "ğŸ‡­ğŸ‡°",
    "maintainer": "EmailOnce",
    "maintainerUrl": "https://email-once.com",
    "online": true,
    "lastChecked": "2025-03-18T23:55:37.330298Z"
  },
  {
    "url": "https://rss.datuan.dev",
    "location": "ğŸ‡»ğŸ‡³",
    "maintainer": "Tuáº¥n Dev",
    "maintainerUrl": "https://duonganhtuan.com",
    "online": true,
    "lastChecked": "2025-03-18T23:55:38.593806Z"
  }
]
